site_name: Citrix StoreFront 3.12 SDK PowerShell Modules
site_description: Citrix StoreFront 3.12 SDK PowerShell Modules
theme_dir: citrix-sdk
markdown_extensions:
  - admonition
  - codehilite(guess_lang=false)
  - toc(permalink=true)
  - footnotes
  - meta

pages:
- Overview: index.md
- Citrix.StoreFront:
    - Overview: Citrix.StoreFront.md
    - Add-STFDeployment: Add-STFDeployment.md
    - Add-STFFeatureState: Add-STFFeatureState.md
    - Add-STFHmacKey: Add-STFHmacKey.md
    - Citrix.StoreFront: Citrix.StoreFront.md
    - Clear-STFDeployment: Clear-STFDeployment.md
    - Clear-STFFeatureStates: Clear-STFFeatureStates.md
    - Export-STFConfiguration: Export-STFConfiguration.md
    - Get-STFDeployment: Get-STFDeployment.md
    - Get-STFDomainService: Get-STFDomainService.md
    - Get-STFFeatureState: Get-STFFeatureState.md
    - Get-STFFeatureStateNames: Get-STFFeatureStateNames.md
    - Get-STFHmacKey: Get-STFHmacKey.md
    - Get-STFInstalledFeatures: Get-STFInstalledFeatures.md
    - Get-STFPackage: Get-STFPackage.md
    - Get-STFPeerResolutionService: Get-STFPeerResolutionService.md
    - Get-STFServerGroup: Get-STFServerGroup.md
    - Get-STFServerGroupJoinState: Get-STFServerGroupJoinState.md
    - Get-STFServiceMonitor: Get-STFServiceMonitor.md
    - Get-STFVersion: Get-STFVersion.md
    - Import-STFConfiguration: Import-STFConfiguration.md
    - Install-STFFeature: Install-STFFeature.md
    - New-STFFeatureState: New-STFFeatureState.md
    - New-STFFeatureStateProperty: New-STFFeatureStateProperty.md
    - Publish-STFServerGroupConfiguration: Publish-STFServerGroupConfiguration.md
    - Remove-STFFeatureState: Remove-STFFeatureState.md
    - Remove-STFHmacKey: Remove-STFHmacKey.md
    - Remove-STFServerGroupMember: Remove-STFServerGroupMember.md
    - Reset-STFFeatureData: Reset-STFFeatureData.md
    - Save-STFService: Save-STFService.md
    - Set-STFDeployment: Set-STFDeployment.md
    - Set-STFDiagnostics: Set-STFDiagnostics.md
    - Set-STFDomainService: Set-STFDomainService.md
    - Set-STFFeatureState: Set-STFFeatureState.md
    - Set-STFServiceMonitor: Set-STFServiceMonitor.md
    - Start-STFServerGroupJoin: Start-STFServerGroupJoin.md
    - Stop-STFServerGroupJoin: Stop-STFServerGroupJoin.md
    - Uninstall-STFFeature: Uninstall-STFFeature.md
    - Unprotect-STFConfigurationExport: Unprotect-STFConfigurationExport.md
    - Update-STFHmacKey: Update-STFHmacKey.md
    - Wait-STFPublishServerGroupConfiguration: Wait-STFPublishServerGroupConfiguration.md
    - Wait-STFServerGroupJoin: Wait-STFServerGroupJoin.md
- Citrix.StoreFront.Authentication:
    - Overview: Citrix.StoreFront.Authentication.md
    - Add-STFAuthenticationService: Add-STFAuthenticationService.md
    - Add-STFAuthenticationServiceProtocol: Add-STFAuthenticationServiceProtocol.md
    - Citrix.StoreFront.Authentication: Citrix.StoreFront.Authentication.md
    - Disable-STFAuthenticationServiceProtocol: Disable-STFAuthenticationServiceProtocol.md
    - Enable-STFAuthenticationServiceProtocol: Enable-STFAuthenticationServiceProtocol.md
    - Get-STFAuthenticationProtocolsAvailable: Get-STFAuthenticationProtocolsAvailable.md
    - Get-STFAuthenticationService: Get-STFAuthenticationService.md
    - Get-STFAuthenticationServiceProtocol: Get-STFAuthenticationServiceProtocol.md
    - Remove-STFAuthenticationService: Remove-STFAuthenticationService.md
    - Remove-STFAuthenticationServiceProtocol: Remove-STFAuthenticationServiceProtocol.md
    - Set-STFClaimsFactoryNames: Set-STFClaimsFactoryNames.md
- Citrix.StoreFront.Authentication.AccountSelfService:
    - Overview: Citrix.StoreFront.Authentication.AccountSelfService.md
    - Get-STFAccountSelfService: Get-STFAccountSelfService.md
    - Set-STFAccountSelfService: Set-STFAccountSelfService.md
- Citrix.StoreFront.Authentication.CitrixAGBasic:
    - Overview: Citrix.StoreFront.Authentication.CitrixAGBasic.md
    - Get-STFCitrixAGBasicOptions: Get-STFCitrixAGBasicOptions.md
    - Set-STFCitrixAGBasicOptions: Set-STFCitrixAGBasicOptions.md
- Citrix.StoreFront.Authentication.Explicit:
    - Overview: Citrix.StoreFront.Authentication.Explicit.md
    - Get-STFExplicitCommonOptions: Get-STFExplicitCommonOptions.md
    - Get-STFExplictJsonAuthCEIP: Get-STFExplictJsonAuthCEIP.md
    - Get-STFExplictJsonEndPoints: Get-STFExplictJsonEndPoints.md
    - Set-STFExplicitCommonOptions: Set-STFExplicitCommonOptions.md
- Citrix.StoreFront.Authentication.PasswordManager:
    - Overview: Citrix.StoreFront.Authentication.PasswordManager.md
    - Get-STFPasswordManagerAccountSelfService: Get-STFPasswordManagerAccountSelfService.md
    - Set-STFPasswordManagerAccountSelfService: Set-STFPasswordManagerAccountSelfService.md
- Citrix.StoreFront.Authentication.PasswordValidator:
    - Overview: Citrix.StoreFront.Authentication.PasswordValidator.md
    - Get-STFExplicitAuthenticator: Get-STFExplicitAuthenticator.md
    - Set-STFExplicitAuthenticator: Set-STFExplicitAuthenticator.md
- Citrix.StoreFront.Authentication.XmlServiceValidator:
    - Overview: Citrix.StoreFront.Authentication.XmlServiceValidator.md
    - Enable-STFXmlServiceAuthentication: Enable-STFXmlServiceAuthentication.md
- Citrix.StoreFront.Roaming:
    - Overview: Citrix.StoreFront.Roaming.md
    - Add-STFRoamingGateway: Add-STFRoamingGateway.md
    - Citrix.StoreFront.Roaming: Citrix.StoreFront.Roaming.md
    - Clear-STFRoamingBeacon: Clear-STFRoamingBeacon.md
    - Get-STFRoamingAccount: Get-STFRoamingAccount.md
    - Get-STFRoamingBeacon: Get-STFRoamingBeacon.md
    - Get-STFRoamingGateway: Get-STFRoamingGateway.md
    - Get-STFRoamingService: Get-STFRoamingService.md
    - Get-STFRoamingServiceRecord: Get-STFRoamingServiceRecord.md
    - Import-STFNetScalerConfiguration: Import-STFNetScalerConfiguration.md
    - New-STFRoamingGateway: New-STFRoamingGateway.md
    - Read-STFNetScalerConfiguration: Read-STFNetScalerConfiguration.md
    - Remove-STFRoamingGateway: Remove-STFRoamingGateway.md
    - Set-STFRoamingAccount: Set-STFRoamingAccount.md
    - Set-STFRoamingBeacon: Set-STFRoamingBeacon.md
    - Set-STFRoamingGateway: Set-STFRoamingGateway.md
    - Test-STFSecureTicketAuthority: Test-STFSecureTicketAuthority.md
    - Update-STFSecureTicketAuthority: Update-STFSecureTicketAuthority.md
- Citrix.StoreFront.Stores:
    - Overview: Citrix.StoreFront.Stores.md
    - Add-STFSessionManagerTrustedIssuer: Add-STFSessionManagerTrustedIssuer.md
    - Add-STFStoreFarm: Add-STFStoreFarm.md
    - Add-STFStoreService: Add-STFStoreService.md
    - Citrix.StoreFront.Stores: Citrix.StoreFront.Stores.md
    - Clear-STFDefaultPnaStore: Clear-STFDefaultPnaStore.md
    - Disable-STFStorePna: Disable-STFStorePna.md
    - Enable-STFStorePna: Enable-STFStorePna.md
    - Get-STFStoreEnumerationOptions: Get-STFStoreEnumerationOptions.md
    - Get-STFStoreFarm: Get-STFStoreFarm.md
    - Get-STFStoreFarmConfiguration: Get-STFStoreFarmConfiguration.md
    - Get-STFStoreGatewayService: Get-STFStoreGatewayService.md
    - Get-STFStoreLaunchOptions: Get-STFStoreLaunchOptions.md
    - Get-STFStorePna: Get-STFStorePna.md
    - Get-STFStorePnaSmartAccess: Get-STFStorePnaSmartAccess.md
    - Get-STFStoreRegisteredGateway: Get-STFStoreRegisteredGateway.md
    - Get-STFStoreRegisteredOptimalLaunchGateway: Get-STFStoreRegisteredOptimalLaunchGateway.md
    - Get-STFStoreService: Get-STFStoreService.md
    - Get-STFStoreSubscriptionsDatabase: Get-STFStoreSubscriptionsDatabase.md
    - Grant-STFStorePnaSmartAccess: Grant-STFStorePnaSmartAccess.md
    - New-STFSessionManagerTrustedIssuer: New-STFSessionManagerTrustedIssuer.md
    - New-STFStoreFarm: New-STFStoreFarm.md
    - Register-STFStoreGateway: Register-STFStoreGateway.md
    - Register-STFStoreOptimalLaunchGateway: Register-STFStoreOptimalLaunchGateway.md
    - Remove-STFSessionManagerTrustedIssuer: Remove-STFSessionManagerTrustedIssuer.md
    - Remove-STFStoreFarm: Remove-STFStoreFarm.md
    - Remove-STFStoreService: Remove-STFStoreService.md
    - Revoke-STFStorePnaSmartAccess: Revoke-STFStorePnaSmartAccess.md
    - Set-STFStoreEnumerationOptions: Set-STFStoreEnumerationOptions.md
    - Set-STFStoreFarm: Set-STFStoreFarm.md
    - Set-STFStoreFarmConfiguration: Set-STFStoreFarmConfiguration.md
    - Set-STFStoreGatewayService: Set-STFStoreGatewayService.md
    - Set-STFStoreLaunchOptions: Set-STFStoreLaunchOptions.md
    - Set-STFStorePnaSmartAccess: Set-STFStorePnaSmartAccess.md
    - Set-STFStoreService: Set-STFStoreService.md
    - Set-STFStoreSubscriptionsDatabase: Set-STFStoreSubscriptionsDatabase.md
    - Unregister-STFStoreGateway: Unregister-STFStoreGateway.md
    - Unregister-STFStoreOptimalLaunchGateway: Unregister-STFStoreOptimalLaunchGateway.md
- Citrix.StoreFront.Stores.MultiSite:
    - Overview: Citrix.StoreFront.Stores.MultiSite.md
    - Add-STFUserFarmMapping: Add-STFUserFarmMapping.md
    - Citrix.StoreFront.Stores.MultiSite: Citrix.StoreFront.Stores.MultiSite.md
    - Clear-STFUserFarmMappings: Clear-STFUserFarmMappings.md
    - Get-STFEquivalentFarmset: Get-STFEquivalentFarmset.md
    - Get-STFUserFarmMapping: Get-STFUserFarmMapping.md
    - New-STFEquivalentFarmset: New-STFEquivalentFarmset.md
    - New-STFUserFarmMappingGroup: New-STFUserFarmMappingGroup.md
    - Remove-STFUserFarmMapping: Remove-STFUserFarmMapping.md
    - Set-STFUserFarmMapping: Set-STFUserFarmMapping.md
- Citrix.StoreFront.SubscriptionsStore:
    - Overview: Citrix.StoreFront.SubscriptionsStore.md
    - Add-STFSubscriptionSynchronizationSchedule: Add-STFSubscriptionSynchronizationSchedule.md
    - Add-STFSubscriptionSynchronizationSource: Add-STFSubscriptionSynchronizationSource.md
    - Citrix.StoreFront.SubscriptionsStore: Citrix.StoreFront.SubscriptionsStore.md
    - Clear-STFSubscriptionSynchronizationSchedule: Clear-STFSubscriptionSynchronizationSchedule.md
    - Clear-STFSubscriptionSynchronizationSource: Clear-STFSubscriptionSynchronizationSource.md
    - Export-STFStoreSubscriptions: Export-STFStoreSubscriptions.md
    - Get-STFComputerSynchronizationPermission: Get-STFComputerSynchronizationPermission.md
    - Get-STFSubscriptionStoreService: Get-STFSubscriptionStoreService.md
    - Get-STFSubscriptionSynchronizationSchedule: Get-STFSubscriptionSynchronizationSchedule.md
    - Get-STFSubscriptionSynchronizationSource: Get-STFSubscriptionSynchronizationSource.md
    - Grant-STFComputerSynchronizationPermission: Grant-STFComputerSynchronizationPermission.md
    - Import-STFStoreSubscriptions: Import-STFStoreSubscriptions.md
    - Remove-STFSubscriptionSynchronizationSource: Remove-STFSubscriptionSynchronizationSource.md
    - Restore-STFStoreSubscriptions: Restore-STFStoreSubscriptions.md
    - Revoke-STFComputerSynchronizationPermission: Revoke-STFComputerSynchronizationPermission.md
- Citrix.StoreFront.WebReceiver:
    - Overview: Citrix.StoreFront.WebReceiver.md
    - Add-STFDesktopApplianceService: Add-STFDesktopApplianceService.md
    - Add-STFWebReceiverClientPlugin: Add-STFWebReceiverClientPlugin.md
    - Add-STFWebReceiverFeature: Add-STFWebReceiverFeature.md
    - Add-STFWebReceiverFeaturedAppGroup: Add-STFWebReceiverFeaturedAppGroup.md
    - Add-STFWebReceiverService: Add-STFWebReceiverService.md
    - Citrix.StoreFront.WebReceiver: Citrix.StoreFront.WebReceiver.md
    - Clear-STFWebReceiverClientPlugin: Clear-STFWebReceiverClientPlugin.md
    - Clear-STFWebReceiverFeaturedAppGroup: Clear-STFWebReceiverFeaturedAppGroup.md
    - Clear-STFWebReceiverSiteStyle: Clear-STFWebReceiverSiteStyle.md
    - Get-STFDesktopApplianceService: Get-STFDesktopApplianceService.md
    - Get-STFIISSitesInfo: Get-STFIISSitesInfo.md
    - Get-STFWebReceiverApplicationShortcuts: Get-STFWebReceiverApplicationShortcuts.md
    - Get-STFWebReceiverAuthenticationManager: Get-STFWebReceiverAuthenticationManager.md
    - Get-STFWebReceiverAuthenticationMethods: Get-STFWebReceiverAuthenticationMethods.md
    - Get-STFWebReceiverAuthenticationMethodsAvailable: Get-STFWebReceiverAuthenticationMethodsAvailable.md
    - Get-STFWebReceiverClientPlugin: Get-STFWebReceiverClientPlugin.md
    - Get-STFWebReceiverCommunication: Get-STFWebReceiverCommunication.md
    - Get-STFWebReceiverDefaultSiteStyle: Get-STFWebReceiverDefaultSiteStyle.md
    - Get-STFWebReceiverDiscoveryService: Get-STFWebReceiverDiscoveryService.md
    - Get-STFWebReceiverFeature: Get-STFWebReceiverFeature.md
    - Get-STFWebReceiverFeaturedAppGroup: Get-STFWebReceiverFeaturedAppGroup.md
    - Get-STFWebReceiverFeaturedAppGroupTiles: Get-STFWebReceiverFeaturedAppGroupTiles.md
    - Get-STFWebReceiverPluginAssistant: Get-STFWebReceiverPluginAssistant.md
    - Get-STFWebReceiverResourcesService: Get-STFWebReceiverResourcesService.md
    - Get-STFWebReceiverService: Get-STFWebReceiverService.md
    - Get-STFWebReceiverSiteStyle: Get-STFWebReceiverSiteStyle.md
    - Get-STFWebReceiverStoreProxy: Get-STFWebReceiverStoreProxy.md
    - Get-STFWebReceiverStrictTransportSecurity: Get-STFWebReceiverStrictTransportSecurity.md
    - Get-STFWebReceiverUserInterface: Get-STFWebReceiverUserInterface.md
    - New-STFWebReceiverClientPlugin: New-STFWebReceiverClientPlugin.md
    - New-STFWebReceiverFeaturedAppGroup: New-STFWebReceiverFeaturedAppGroup.md
    - Remove-STFDesktopApplianceService: Remove-STFDesktopApplianceService.md
    - Remove-STFWebReceiverClientPlugin: Remove-STFWebReceiverClientPlugin.md
    - Remove-STFWebReceiverFeature: Remove-STFWebReceiverFeature.md
    - Remove-STFWebReceiverFeaturedAppGroup: Remove-STFWebReceiverFeaturedAppGroup.md
    - Remove-STFWebReceiverService: Remove-STFWebReceiverService.md
    - Set-STFDesktopApplianceService: Set-STFDesktopApplianceService.md
    - Set-STFWebReceiverApplicationShortcuts: Set-STFWebReceiverApplicationShortcuts.md
    - Set-STFWebReceiverAuthenticationManager: Set-STFWebReceiverAuthenticationManager.md
    - Set-STFWebReceiverAuthenticationMethods: Set-STFWebReceiverAuthenticationMethods.md
    - Set-STFWebReceiverClientPlugin: Set-STFWebReceiverClientPlugin.md
    - Set-STFWebReceiverCommunication: Set-STFWebReceiverCommunication.md
    - Set-STFWebReceiverDiscoveryService: Set-STFWebReceiverDiscoveryService.md
    - Set-STFWebReceiverFeaturedAppGroup: Set-STFWebReceiverFeaturedAppGroup.md
    - Set-STFWebReceiverFeaturedAppGroups: Set-STFWebReceiverFeaturedAppGroups.md
    - Set-STFWebReceiverPluginAssistant: Set-STFWebReceiverPluginAssistant.md
    - Set-STFWebReceiverResourcesService: Set-STFWebReceiverResourcesService.md
    - Set-STFWebReceiverService: Set-STFWebReceiverService.md
    - Set-STFWebReceiverSiteStyle: Set-STFWebReceiverSiteStyle.md
    - Set-STFWebReceiverStrictTransportSecurity: Set-STFWebReceiverStrictTransportSecurity.md
    - Set-STFWebReceiverUserInterface: Set-STFWebReceiverUserInterface.md
